trigger: 
 - master

pool:
   vmImage: 'ubuntu-latest'

stages:
- stage: Build
  displayName: Build and push stage
  jobs:
  - job: BuildJob
    displayName: Build
    steps:
    
    - task: GoTool@0
      inputs:
        version: '1.17'
    
    - task: Go@0
      inputs:
        command: 'get'
        arguments: '-v -d'
        workingDirectory: server
    
    - task: Go@0
      inputs:
        command: 'build'
        arguments: '-v -o api'
        workingDirectory: server

    - task: PublishPipelineArtifact@1
      displayName: "Publish Pipeline Artifact"
      inputs:
        targetPath: server/main
        artifact: "server-bin"