using Go = import "/go.capnp";

@0xd7269f09fb7ba87a;
# unique file ID, generated by `capnp id`

$Go.package("hashes");
$Go.import("foo/hashes");


interface HashFactory {
  newSha1 @0 () -> (hash :Hash);
}

interface Hash {
  write @0 (data :Data) -> ();
  sum @1 () -> (hash :Data);
}