/*
 * MeshX Cloud API
 *
 * MeshX Cloud API
 *
 * The version of the OpenAPI document: 0.1.0-beta
 * Contact: hello@meshx.co
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreateHostgroupDto {
    #[serde(rename = "data")]
    pub data: Box<models::CreateHostgroupDtoData>,
}

impl CreateHostgroupDto {
    pub fn new(data: models::CreateHostgroupDtoData) -> CreateHostgroupDto {
        CreateHostgroupDto {
            data: Box::new(data),
        }
    }
}

