/*
 * MeshX Cloud API
 *
 * MeshX Cloud API
 *
 * The version of the OpenAPI document: 0.1.0-beta
 * Contact: hello@meshx.co
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreateHostgroupDtoData {
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "project")]
    pub project: f64,
    #[serde(rename = "instance")]
    pub instance: Box<models::CreateHostgroupDtoDataInstance>,
    #[serde(rename = "desired_replicas")]
    pub desired_replicas: f64,
}

impl CreateHostgroupDtoData {
    pub fn new(
        name: String,
        project: f64,
        instance: models::CreateHostgroupDtoDataInstance,
        desired_replicas: f64,
    ) -> CreateHostgroupDtoData {
        CreateHostgroupDtoData {
            name,
            project,
            instance: Box::new(instance),
            desired_replicas,
        }
    }
}
