/*
 * MeshX Cloud API
 *
 * MeshX Cloud API
 *
 * The version of the OpenAPI document: 0.1.0-beta
 * Contact: hello@meshx.co
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreateHostgroupDtoDataInstance {
    #[serde(rename = "type")]
    pub r#type: Type,
    #[serde(rename = "vcpu_count")]
    pub vcpu_count: f64,
    #[serde(rename = "ram_mib")]
    pub ram_mib: f64,
}

impl CreateHostgroupDtoDataInstance {
    pub fn new(r#type: Type, vcpu_count: f64, ram_mib: f64) -> CreateHostgroupDtoDataInstance {
        CreateHostgroupDtoDataInstance {
            r#type,
            vcpu_count,
            ram_mib,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "burst-gen1")]
    BurstGen1,
    #[serde(rename = "perf-gen1")]
    PerfGen1,
}

impl Default for Type {
    fn default() -> Type {
        Self::BurstGen1
    }
}

