/*
 * MeshX Cloud API
 *
 * MeshX Cloud API
 *
 * The version of the OpenAPI document: 0.1.0-beta
 * Contact: hello@meshx.co
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreateHostDtoData {
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "project")]
    pub project: f64,
    #[serde(rename = "cpu_count")]
    pub cpu_count: i32,
    #[serde(rename = "cpu_kind")]
    pub cpu_kind: CpuKind,
    #[serde(rename = "ram_mb")]
    pub ram_mb: i32,
}

impl CreateHostDtoData {
    pub fn new(
        name: String,
        project: f64,
        cpu_count: i32,
        cpu_kind: CpuKind,
        ram_mb: i32,
    ) -> CreateHostDtoData {
        CreateHostDtoData {
            name,
            project,
            cpu_count,
            cpu_kind,
            ram_mb,
        }
    }
}
///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum CpuKind {
    #[serde(rename = "burst")]
    Burst,
    #[serde(rename = "dedicated")]
    Dedicated,
}

impl Default for CpuKind {
    fn default() -> CpuKind {
        Self::Burst
    }
}
