/*
 * MeshX Cloud API
 *
 * MeshX Cloud API
 *
 * The version of the OpenAPI document: 0.1.0-beta
 * Contact: hello@meshx.co
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreateServiceDtoData {
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "project")]
    pub project: f64,
    #[serde(rename = "host")]
    pub host: String,
    #[serde(rename = "type")]
    pub r#type: String,
}

impl CreateServiceDtoData {
    pub fn new(name: String, project: f64, host: String, r#type: String) -> CreateServiceDtoData {
        CreateServiceDtoData {
            name,
            project,
            host,
            r#type,
        }
    }
}

