/*
 * MeshX Cloud API
 *
 * MeshX Cloud API
 *
 * The version of the OpenAPI document: 0.1.0-beta
 * Contact: hello@meshx.co
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ServiceDtoOutput {
    #[serde(rename = "id")]
    pub id: f64,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "createdAt")]
    pub created_at: String,
    #[serde(rename = "updatedAt")]
    pub updated_at: String,
    #[serde(rename = "projectId")]
    pub project_id: f64,
    #[serde(rename = "hostId")]
    pub host_id: String,
}

impl ServiceDtoOutput {
    pub fn new(
        id: f64,
        name: String,
        created_at: String,
        updated_at: String,
        project_id: f64,
        host_id: String,
    ) -> ServiceDtoOutput {
        ServiceDtoOutput {
            id,
            name,
            created_at,
            updated_at,
            project_id,
            host_id,
        }
    }
}
