/*
 * MeshX Cloud API
 *
 * MeshX Cloud API
 *
 * The version of the OpenAPI document: 0.1.0-beta
 * Contact: hello@meshx.co
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct WorkloadCreateRequestDtoDataHostInterfacesInner {
    #[serde(rename = "namespace")]
    pub namespace: String,
    #[serde(rename = "package")]
    pub package: String,
    #[serde(rename = "interfaces")]
    pub interfaces: Vec<String>,
    #[serde(rename = "config")]
    pub config: std::collections::HashMap<String, String>,
}

impl WorkloadCreateRequestDtoDataHostInterfacesInner {
    pub fn new(namespace: String, package: String, interfaces: Vec<String>, config: std::collections::HashMap<String, String>) -> WorkloadCreateRequestDtoDataHostInterfacesInner {
        WorkloadCreateRequestDtoDataHostInterfacesInner {
            namespace,
            package,
            interfaces,
            config,
        }
    }
}

