/*
 * MeshX Cloud API
 *
 * MeshX Cloud API
 *
 * The version of the OpenAPI document: 0.1.0-beta
 * Contact: hello@meshx.co
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct WorkloadCreateResponseDtoOutputDataVolumesInnerVolumeTypeAnyOf1 {
    #[serde(rename = "emptyDir")]
    pub empty_dir: serde_json::Value,
}

impl WorkloadCreateResponseDtoOutputDataVolumesInnerVolumeTypeAnyOf1 {
    pub fn new(
        empty_dir: serde_json::Value,
    ) -> WorkloadCreateResponseDtoOutputDataVolumesInnerVolumeTypeAnyOf1 {
        WorkloadCreateResponseDtoOutputDataVolumesInnerVolumeTypeAnyOf1 { empty_dir }
    }
}
