/*
 * MeshX Cloud API
 *
 * MeshX Cloud API
 *
 * The version of the OpenAPI document: 0.1.0-beta
 * Contact: hello@meshx.co
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct WorkloadCreateResponseDtoOutputDataVolumesInnerVolumeTypeAnyOf {
    #[serde(rename = "hostPath")]
    pub host_path:
        Box<models::WorkloadCreateResponseDtoOutputDataVolumesInnerVolumeTypeAnyOfHostPath>,
}

impl WorkloadCreateResponseDtoOutputDataVolumesInnerVolumeTypeAnyOf {
    pub fn new(
        host_path: models::WorkloadCreateResponseDtoOutputDataVolumesInnerVolumeTypeAnyOfHostPath,
    ) -> WorkloadCreateResponseDtoOutputDataVolumesInnerVolumeTypeAnyOf {
        WorkloadCreateResponseDtoOutputDataVolumesInnerVolumeTypeAnyOf {
            host_path: Box::new(host_path),
        }
    }
}
