/*
 * MeshX Cloud API
 *
 * MeshX Cloud API
 *
 * The version of the OpenAPI document: 0.1.0-beta
 * Contact: hello@meshx.co
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct WorkloadCreateRequestDtoDataVolumesInnerVolumeTypeAnyOfHostPath {
    #[serde(rename = "local_path")]
    pub local_path: String,
}

impl WorkloadCreateRequestDtoDataVolumesInnerVolumeTypeAnyOfHostPath {
    pub fn new(
        local_path: String,
    ) -> WorkloadCreateRequestDtoDataVolumesInnerVolumeTypeAnyOfHostPath {
        WorkloadCreateRequestDtoDataVolumesInnerVolumeTypeAnyOfHostPath { local_path }
    }
}
