/*
 * MeshX Cloud API
 *
 * MeshX Cloud API
 *
 * The version of the OpenAPI document: 0.1.0-beta
 * Contact: hello@meshx.co
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct WorkloadCreateResponseDtoOutputDataVolumesInner {
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "volumeType")]
    pub volume_type: Box<models::WorkloadCreateResponseDtoOutputDataVolumesInnerVolumeType>,
}

impl WorkloadCreateResponseDtoOutputDataVolumesInner {
    pub fn new(
        name: String,
        volume_type: models::WorkloadCreateResponseDtoOutputDataVolumesInnerVolumeType,
    ) -> WorkloadCreateResponseDtoOutputDataVolumesInner {
        WorkloadCreateResponseDtoOutputDataVolumesInner {
            name,
            volume_type: Box::new(volume_type),
        }
    }
}
