/*
 * MeshX Cloud API
 *
 * MeshX Cloud API
 *
 * The version of the OpenAPI document: 0.1.0-beta
 * Contact: hello@meshx.co
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct WorkloadCreateResponseDtoOutputData {
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "annotations", skip_serializing_if = "Option::is_none")]
    pub annotations: Option<std::collections::HashMap<String, String>>,
    #[serde(rename = "service", skip_serializing_if = "Option::is_none")]
    pub service: Option<Box<models::WorkloadCreateResponseDtoOutputDataService>>,
    #[serde(rename = "components")]
    pub components: Vec<models::WorkloadCreateResponseDtoOutputDataComponentsInner>,
    #[serde(rename = "hostInterfaces")]
    pub host_interfaces: Vec<models::WorkloadCreateResponseDtoOutputDataHostInterfacesInner>,
    #[serde(rename = "volumes", skip_serializing_if = "Option::is_none")]
    pub volumes: Option<Vec<models::WorkloadCreateResponseDtoOutputDataVolumesInner>>,
}

impl WorkloadCreateResponseDtoOutputData {
    pub fn new(name: String, components: Vec<models::WorkloadCreateResponseDtoOutputDataComponentsInner>, host_interfaces: Vec<models::WorkloadCreateResponseDtoOutputDataHostInterfacesInner>) -> WorkloadCreateResponseDtoOutputData {
        WorkloadCreateResponseDtoOutputData {
            name,
            annotations: None,
            service: None,
            components,
            host_interfaces,
            volumes: None,
        }
    }
}

