/*
 * MeshX Cloud API
 *
 * MeshX Cloud API
 *
 * The version of the OpenAPI document: 0.1.0-beta
 * Contact: hello@meshx.co
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct WorkloadCreateRequestDtoDataService {
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "image")]
    pub image: String,
    #[serde(rename = "maxRestarts")]
    pub max_restarts: f64,
}

impl WorkloadCreateRequestDtoDataService {
    pub fn new(name: String, image: String, max_restarts: f64) -> WorkloadCreateRequestDtoDataService {
        WorkloadCreateRequestDtoDataService {
            name,
            image,
            max_restarts,
        }
    }
}

