/*
 * MeshX Cloud API
 *
 * MeshX Cloud API
 *
 * The version of the OpenAPI document: 0.1.0-beta
 * Contact: hello@meshx.co
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct WorkloadCreateResponseDtoOutputDataVolumesInnerVolumeType {
    #[serde(rename = "hostPath")]
    pub host_path:
        Box<models::WorkloadCreateResponseDtoOutputDataVolumesInnerVolumeTypeAnyOfHostPath>,
    #[serde(rename = "emptyDir")]
    pub empty_dir: serde_json::Value,
}

impl WorkloadCreateResponseDtoOutputDataVolumesInnerVolumeType {
    pub fn new(
        host_path: models::WorkloadCreateResponseDtoOutputDataVolumesInnerVolumeTypeAnyOfHostPath,
        empty_dir: serde_json::Value,
    ) -> WorkloadCreateResponseDtoOutputDataVolumesInnerVolumeType {
        WorkloadCreateResponseDtoOutputDataVolumesInnerVolumeType {
            host_path: Box::new(host_path),
            empty_dir,
        }
    }
}
