/*
 * MeshX Cloud API
 *
 * MeshX Cloud API
 *
 * The version of the OpenAPI document: 0.1.0-beta
 * Contact: hello@meshx.co
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct WorkloadCreateRequestDtoDataComponentsInner {
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "image")]
    pub image: String,
    #[serde(rename = "poolSize")]
    pub pool_size: f64,
    #[serde(rename = "maxInvocations")]
    pub max_invocations: f64,
}

impl WorkloadCreateRequestDtoDataComponentsInner {
    pub fn new(
        name: String,
        image: String,
        pool_size: f64,
        max_invocations: f64,
    ) -> WorkloadCreateRequestDtoDataComponentsInner {
        WorkloadCreateRequestDtoDataComponentsInner {
            name,
            image,
            pool_size,
            max_invocations,
        }
    }
}
