// Code generated by capnpc-go. DO NOT EDIT.

package resource_store

import (
	capnp "capnproto.org/go/capnp/v3"
	text "capnproto.org/go/capnp/v3/encoding/text"
	schemas "capnproto.org/go/capnp/v3/schemas"
	server "capnproto.org/go/capnp/v3/server"
	context "context"
)

type ResourceObject struct{ capnp.Struct }

// ResourceObject_TypeID is the unique identifier for the type ResourceObject.
const ResourceObject_TypeID = 0xb7b365704803e243

func NewResourceObject(s *capnp.Segment) (ResourceObject, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 3})
	return ResourceObject{st}, err
}

func NewRootResourceObject(s *capnp.Segment) (ResourceObject, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 3})
	return ResourceObject{st}, err
}

func ReadRootResourceObject(msg *capnp.Message) (ResourceObject, error) {
	root, err := msg.Root()
	return ResourceObject{root.Struct()}, err
}

func (s ResourceObject) String() string {
	str, _ := text.Marshal(0xb7b365704803e243, s.Struct)
	return str
}

func (s ResourceObject) ApiVersion() (string, error) {
	p, err := s.Struct.Ptr(0)
	return p.Text(), err
}

func (s ResourceObject) HasApiVersion() bool {
	return s.Struct.HasPtr(0)
}

func (s ResourceObject) ApiVersionBytes() ([]byte, error) {
	p, err := s.Struct.Ptr(0)
	return p.TextBytes(), err
}

func (s ResourceObject) SetApiVersion(v string) error {
	return s.Struct.SetText(0, v)
}

func (s ResourceObject) Spec() (capnp.Ptr, error) {
	return s.Struct.Ptr(1)
}

func (s ResourceObject) HasSpec() bool {
	return s.Struct.HasPtr(1)
}

func (s ResourceObject) SetSpec(v capnp.Ptr) error {
	return s.Struct.SetPtr(1, v)
}

func (s ResourceObject) Status() (capnp.Ptr, error) {
	return s.Struct.Ptr(2)
}

func (s ResourceObject) HasStatus() bool {
	return s.Struct.HasPtr(2)
}

func (s ResourceObject) SetStatus(v capnp.Ptr) error {
	return s.Struct.SetPtr(2, v)
}

// ResourceObject_List is a list of ResourceObject.
type ResourceObject_List struct{ capnp.List }

// NewResourceObject creates a new list of ResourceObject.
func NewResourceObject_List(s *capnp.Segment, sz int32) (ResourceObject_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 3}, sz)
	return ResourceObject_List{l}, err
}

func (s ResourceObject_List) At(i int) ResourceObject { return ResourceObject{s.List.Struct(i)} }

func (s ResourceObject_List) Set(i int, v ResourceObject) error { return s.List.SetStruct(i, v.Struct) }

func (s ResourceObject_List) String() string {
	str, _ := text.MarshalList(0xb7b365704803e243, s.List)
	return str
}

// ResourceObject_Future is a wrapper for a ResourceObject promised by a client call.
type ResourceObject_Future struct{ *capnp.Future }

func (p ResourceObject_Future) Struct() (ResourceObject, error) {
	s, err := p.Future.Struct()
	return ResourceObject{s}, err
}

func (p ResourceObject_Future) Spec() *capnp.Future {
	return p.Future.Field(1, nil)
}

func (p ResourceObject_Future) Status() *capnp.Future {
	return p.Future.Field(2, nil)
}

type ResourceKind struct{ Client *capnp.Client }

// ResourceKind_TypeID is the unique identifier for the type ResourceKind.
const ResourceKind_TypeID = 0xd66bdb575be45eb8

func (c ResourceKind) GetObject(ctx context.Context, params func(ResourceKind_getObject_Params) error) (ResourceKind_getObject_Results_Future, capnp.ReleaseFunc) {
	s := capnp.Send{
		Method: capnp.Method{
			InterfaceID:   0xd66bdb575be45eb8,
			MethodID:      0,
			InterfaceName: "protocol/resource-store.capnp:ResourceKind",
			MethodName:    "getObject",
		},
	}
	if params != nil {
		s.ArgsSize = capnp.ObjectSize{DataSize: 0, PointerCount: 0}
		s.PlaceArgs = func(s capnp.Struct) error { return params(ResourceKind_getObject_Params{Struct: s}) }
	}
	ans, release := c.Client.SendCall(ctx, s)
	return ResourceKind_getObject_Results_Future{Future: ans.Future()}, release
}
func (c ResourceKind) CreateObject(ctx context.Context, params func(ResourceKind_createObject_Params) error) (ResourceKind_createObject_Results_Future, capnp.ReleaseFunc) {
	s := capnp.Send{
		Method: capnp.Method{
			InterfaceID:   0xd66bdb575be45eb8,
			MethodID:      1,
			InterfaceName: "protocol/resource-store.capnp:ResourceKind",
			MethodName:    "createObject",
		},
	}
	if params != nil {
		s.ArgsSize = capnp.ObjectSize{DataSize: 0, PointerCount: 1}
		s.PlaceArgs = func(s capnp.Struct) error { return params(ResourceKind_createObject_Params{Struct: s}) }
	}
	ans, release := c.Client.SendCall(ctx, s)
	return ResourceKind_createObject_Results_Future{Future: ans.Future()}, release
}

func (c ResourceKind) AddRef() ResourceKind {
	return ResourceKind{
		Client: c.Client.AddRef(),
	}
}

func (c ResourceKind) Release() {
	c.Client.Release()
}

// A ResourceKind_Server is a ResourceKind with a local implementation.
type ResourceKind_Server interface {
	GetObject(context.Context, ResourceKind_getObject) error

	CreateObject(context.Context, ResourceKind_createObject) error
}

// ResourceKind_NewServer creates a new Server from an implementation of ResourceKind_Server.
func ResourceKind_NewServer(s ResourceKind_Server, policy *server.Policy) *server.Server {
	c, _ := s.(server.Shutdowner)
	return server.New(ResourceKind_Methods(nil, s), s, c, policy)
}

// ResourceKind_ServerToClient creates a new Client from an implementation of ResourceKind_Server.
// The caller is responsible for calling Release on the returned Client.
func ResourceKind_ServerToClient(s ResourceKind_Server, policy *server.Policy) ResourceKind {
	return ResourceKind{Client: capnp.NewClient(ResourceKind_NewServer(s, policy))}
}

// ResourceKind_Methods appends Methods to a slice that invoke the methods on s.
// This can be used to create a more complicated Server.
func ResourceKind_Methods(methods []server.Method, s ResourceKind_Server) []server.Method {
	if cap(methods) == 0 {
		methods = make([]server.Method, 0, 2)
	}

	methods = append(methods, server.Method{
		Method: capnp.Method{
			InterfaceID:   0xd66bdb575be45eb8,
			MethodID:      0,
			InterfaceName: "protocol/resource-store.capnp:ResourceKind",
			MethodName:    "getObject",
		},
		Impl: func(ctx context.Context, call *server.Call) error {
			return s.GetObject(ctx, ResourceKind_getObject{call})
		},
	})

	methods = append(methods, server.Method{
		Method: capnp.Method{
			InterfaceID:   0xd66bdb575be45eb8,
			MethodID:      1,
			InterfaceName: "protocol/resource-store.capnp:ResourceKind",
			MethodName:    "createObject",
		},
		Impl: func(ctx context.Context, call *server.Call) error {
			return s.CreateObject(ctx, ResourceKind_createObject{call})
		},
	})

	return methods
}

// ResourceKind_getObject holds the state for a server call to ResourceKind.getObject.
// See server.Call for documentation.
type ResourceKind_getObject struct {
	*server.Call
}

// Args returns the call's arguments.
func (c ResourceKind_getObject) Args() ResourceKind_getObject_Params {
	return ResourceKind_getObject_Params{Struct: c.Call.Args()}
}

// AllocResults allocates the results struct.
func (c ResourceKind_getObject) AllocResults() (ResourceKind_getObject_Results, error) {
	r, err := c.Call.AllocResults(capnp.ObjectSize{DataSize: 0, PointerCount: 1})
	return ResourceKind_getObject_Results{Struct: r}, err
}

// ResourceKind_createObject holds the state for a server call to ResourceKind.createObject.
// See server.Call for documentation.
type ResourceKind_createObject struct {
	*server.Call
}

// Args returns the call's arguments.
func (c ResourceKind_createObject) Args() ResourceKind_createObject_Params {
	return ResourceKind_createObject_Params{Struct: c.Call.Args()}
}

// AllocResults allocates the results struct.
func (c ResourceKind_createObject) AllocResults() (ResourceKind_createObject_Results, error) {
	r, err := c.Call.AllocResults(capnp.ObjectSize{DataSize: 0, PointerCount: 0})
	return ResourceKind_createObject_Results{Struct: r}, err
}

type ResourceKind_getObject_Params struct{ capnp.Struct }

// ResourceKind_getObject_Params_TypeID is the unique identifier for the type ResourceKind_getObject_Params.
const ResourceKind_getObject_Params_TypeID = 0x85960434116355cb

func NewResourceKind_getObject_Params(s *capnp.Segment) (ResourceKind_getObject_Params, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0})
	return ResourceKind_getObject_Params{st}, err
}

func NewRootResourceKind_getObject_Params(s *capnp.Segment) (ResourceKind_getObject_Params, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0})
	return ResourceKind_getObject_Params{st}, err
}

func ReadRootResourceKind_getObject_Params(msg *capnp.Message) (ResourceKind_getObject_Params, error) {
	root, err := msg.Root()
	return ResourceKind_getObject_Params{root.Struct()}, err
}

func (s ResourceKind_getObject_Params) String() string {
	str, _ := text.Marshal(0x85960434116355cb, s.Struct)
	return str
}

// ResourceKind_getObject_Params_List is a list of ResourceKind_getObject_Params.
type ResourceKind_getObject_Params_List struct{ capnp.List }

// NewResourceKind_getObject_Params creates a new list of ResourceKind_getObject_Params.
func NewResourceKind_getObject_Params_List(s *capnp.Segment, sz int32) (ResourceKind_getObject_Params_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0}, sz)
	return ResourceKind_getObject_Params_List{l}, err
}

func (s ResourceKind_getObject_Params_List) At(i int) ResourceKind_getObject_Params {
	return ResourceKind_getObject_Params{s.List.Struct(i)}
}

func (s ResourceKind_getObject_Params_List) Set(i int, v ResourceKind_getObject_Params) error {
	return s.List.SetStruct(i, v.Struct)
}

func (s ResourceKind_getObject_Params_List) String() string {
	str, _ := text.MarshalList(0x85960434116355cb, s.List)
	return str
}

// ResourceKind_getObject_Params_Future is a wrapper for a ResourceKind_getObject_Params promised by a client call.
type ResourceKind_getObject_Params_Future struct{ *capnp.Future }

func (p ResourceKind_getObject_Params_Future) Struct() (ResourceKind_getObject_Params, error) {
	s, err := p.Future.Struct()
	return ResourceKind_getObject_Params{s}, err
}

type ResourceKind_getObject_Results struct{ capnp.Struct }

// ResourceKind_getObject_Results_TypeID is the unique identifier for the type ResourceKind_getObject_Results.
const ResourceKind_getObject_Results_TypeID = 0xffa6c4576be32489

func NewResourceKind_getObject_Results(s *capnp.Segment) (ResourceKind_getObject_Results, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1})
	return ResourceKind_getObject_Results{st}, err
}

func NewRootResourceKind_getObject_Results(s *capnp.Segment) (ResourceKind_getObject_Results, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1})
	return ResourceKind_getObject_Results{st}, err
}

func ReadRootResourceKind_getObject_Results(msg *capnp.Message) (ResourceKind_getObject_Results, error) {
	root, err := msg.Root()
	return ResourceKind_getObject_Results{root.Struct()}, err
}

func (s ResourceKind_getObject_Results) String() string {
	str, _ := text.Marshal(0xffa6c4576be32489, s.Struct)
	return str
}

func (s ResourceKind_getObject_Results) Value() (ResourceObject, error) {
	p, err := s.Struct.Ptr(0)
	return ResourceObject{Struct: p.Struct()}, err
}

func (s ResourceKind_getObject_Results) HasValue() bool {
	return s.Struct.HasPtr(0)
}

func (s ResourceKind_getObject_Results) SetValue(v ResourceObject) error {
	return s.Struct.SetPtr(0, v.Struct.ToPtr())
}

// NewValue sets the value field to a newly
// allocated ResourceObject struct, preferring placement in s's segment.
func (s ResourceKind_getObject_Results) NewValue() (ResourceObject, error) {
	ss, err := NewResourceObject(s.Struct.Segment())
	if err != nil {
		return ResourceObject{}, err
	}
	err = s.Struct.SetPtr(0, ss.Struct.ToPtr())
	return ss, err
}

// ResourceKind_getObject_Results_List is a list of ResourceKind_getObject_Results.
type ResourceKind_getObject_Results_List struct{ capnp.List }

// NewResourceKind_getObject_Results creates a new list of ResourceKind_getObject_Results.
func NewResourceKind_getObject_Results_List(s *capnp.Segment, sz int32) (ResourceKind_getObject_Results_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1}, sz)
	return ResourceKind_getObject_Results_List{l}, err
}

func (s ResourceKind_getObject_Results_List) At(i int) ResourceKind_getObject_Results {
	return ResourceKind_getObject_Results{s.List.Struct(i)}
}

func (s ResourceKind_getObject_Results_List) Set(i int, v ResourceKind_getObject_Results) error {
	return s.List.SetStruct(i, v.Struct)
}

func (s ResourceKind_getObject_Results_List) String() string {
	str, _ := text.MarshalList(0xffa6c4576be32489, s.List)
	return str
}

// ResourceKind_getObject_Results_Future is a wrapper for a ResourceKind_getObject_Results promised by a client call.
type ResourceKind_getObject_Results_Future struct{ *capnp.Future }

func (p ResourceKind_getObject_Results_Future) Struct() (ResourceKind_getObject_Results, error) {
	s, err := p.Future.Struct()
	return ResourceKind_getObject_Results{s}, err
}

func (p ResourceKind_getObject_Results_Future) Value() ResourceObject_Future {
	return ResourceObject_Future{Future: p.Future.Field(0, nil)}
}

type ResourceKind_createObject_Params struct{ capnp.Struct }

// ResourceKind_createObject_Params_TypeID is the unique identifier for the type ResourceKind_createObject_Params.
const ResourceKind_createObject_Params_TypeID = 0xab24ffe523b0c72d

func NewResourceKind_createObject_Params(s *capnp.Segment) (ResourceKind_createObject_Params, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1})
	return ResourceKind_createObject_Params{st}, err
}

func NewRootResourceKind_createObject_Params(s *capnp.Segment) (ResourceKind_createObject_Params, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1})
	return ResourceKind_createObject_Params{st}, err
}

func ReadRootResourceKind_createObject_Params(msg *capnp.Message) (ResourceKind_createObject_Params, error) {
	root, err := msg.Root()
	return ResourceKind_createObject_Params{root.Struct()}, err
}

func (s ResourceKind_createObject_Params) String() string {
	str, _ := text.Marshal(0xab24ffe523b0c72d, s.Struct)
	return str
}

func (s ResourceKind_createObject_Params) Value() (ResourceObject, error) {
	p, err := s.Struct.Ptr(0)
	return ResourceObject{Struct: p.Struct()}, err
}

func (s ResourceKind_createObject_Params) HasValue() bool {
	return s.Struct.HasPtr(0)
}

func (s ResourceKind_createObject_Params) SetValue(v ResourceObject) error {
	return s.Struct.SetPtr(0, v.Struct.ToPtr())
}

// NewValue sets the value field to a newly
// allocated ResourceObject struct, preferring placement in s's segment.
func (s ResourceKind_createObject_Params) NewValue() (ResourceObject, error) {
	ss, err := NewResourceObject(s.Struct.Segment())
	if err != nil {
		return ResourceObject{}, err
	}
	err = s.Struct.SetPtr(0, ss.Struct.ToPtr())
	return ss, err
}

// ResourceKind_createObject_Params_List is a list of ResourceKind_createObject_Params.
type ResourceKind_createObject_Params_List struct{ capnp.List }

// NewResourceKind_createObject_Params creates a new list of ResourceKind_createObject_Params.
func NewResourceKind_createObject_Params_List(s *capnp.Segment, sz int32) (ResourceKind_createObject_Params_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1}, sz)
	return ResourceKind_createObject_Params_List{l}, err
}

func (s ResourceKind_createObject_Params_List) At(i int) ResourceKind_createObject_Params {
	return ResourceKind_createObject_Params{s.List.Struct(i)}
}

func (s ResourceKind_createObject_Params_List) Set(i int, v ResourceKind_createObject_Params) error {
	return s.List.SetStruct(i, v.Struct)
}

func (s ResourceKind_createObject_Params_List) String() string {
	str, _ := text.MarshalList(0xab24ffe523b0c72d, s.List)
	return str
}

// ResourceKind_createObject_Params_Future is a wrapper for a ResourceKind_createObject_Params promised by a client call.
type ResourceKind_createObject_Params_Future struct{ *capnp.Future }

func (p ResourceKind_createObject_Params_Future) Struct() (ResourceKind_createObject_Params, error) {
	s, err := p.Future.Struct()
	return ResourceKind_createObject_Params{s}, err
}

func (p ResourceKind_createObject_Params_Future) Value() ResourceObject_Future {
	return ResourceObject_Future{Future: p.Future.Field(0, nil)}
}

type ResourceKind_createObject_Results struct{ capnp.Struct }

// ResourceKind_createObject_Results_TypeID is the unique identifier for the type ResourceKind_createObject_Results.
const ResourceKind_createObject_Results_TypeID = 0xdad9d20656de1d95

func NewResourceKind_createObject_Results(s *capnp.Segment) (ResourceKind_createObject_Results, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0})
	return ResourceKind_createObject_Results{st}, err
}

func NewRootResourceKind_createObject_Results(s *capnp.Segment) (ResourceKind_createObject_Results, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0})
	return ResourceKind_createObject_Results{st}, err
}

func ReadRootResourceKind_createObject_Results(msg *capnp.Message) (ResourceKind_createObject_Results, error) {
	root, err := msg.Root()
	return ResourceKind_createObject_Results{root.Struct()}, err
}

func (s ResourceKind_createObject_Results) String() string {
	str, _ := text.Marshal(0xdad9d20656de1d95, s.Struct)
	return str
}

// ResourceKind_createObject_Results_List is a list of ResourceKind_createObject_Results.
type ResourceKind_createObject_Results_List struct{ capnp.List }

// NewResourceKind_createObject_Results creates a new list of ResourceKind_createObject_Results.
func NewResourceKind_createObject_Results_List(s *capnp.Segment, sz int32) (ResourceKind_createObject_Results_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0}, sz)
	return ResourceKind_createObject_Results_List{l}, err
}

func (s ResourceKind_createObject_Results_List) At(i int) ResourceKind_createObject_Results {
	return ResourceKind_createObject_Results{s.List.Struct(i)}
}

func (s ResourceKind_createObject_Results_List) Set(i int, v ResourceKind_createObject_Results) error {
	return s.List.SetStruct(i, v.Struct)
}

func (s ResourceKind_createObject_Results_List) String() string {
	str, _ := text.MarshalList(0xdad9d20656de1d95, s.List)
	return str
}

// ResourceKind_createObject_Results_Future is a wrapper for a ResourceKind_createObject_Results promised by a client call.
type ResourceKind_createObject_Results_Future struct{ *capnp.Future }

func (p ResourceKind_createObject_Results_Future) Struct() (ResourceKind_createObject_Results, error) {
	s, err := p.Future.Struct()
	return ResourceKind_createObject_Results{s}, err
}

type ResourceStore struct{ Client *capnp.Client }

// ResourceStore_TypeID is the unique identifier for the type ResourceStore.
const ResourceStore_TypeID = 0x890d6d36373c01d5

func (c ResourceStore) GetKind(ctx context.Context, params func(ResourceStore_getKind_Params) error) (ResourceStore_getKind_Results_Future, capnp.ReleaseFunc) {
	s := capnp.Send{
		Method: capnp.Method{
			InterfaceID:   0x890d6d36373c01d5,
			MethodID:      0,
			InterfaceName: "protocol/resource-store.capnp:ResourceStore",
			MethodName:    "getKind",
		},
	}
	if params != nil {
		s.ArgsSize = capnp.ObjectSize{DataSize: 0, PointerCount: 1}
		s.PlaceArgs = func(s capnp.Struct) error { return params(ResourceStore_getKind_Params{Struct: s}) }
	}
	ans, release := c.Client.SendCall(ctx, s)
	return ResourceStore_getKind_Results_Future{Future: ans.Future()}, release
}

func (c ResourceStore) AddRef() ResourceStore {
	return ResourceStore{
		Client: c.Client.AddRef(),
	}
}

func (c ResourceStore) Release() {
	c.Client.Release()
}

// A ResourceStore_Server is a ResourceStore with a local implementation.
type ResourceStore_Server interface {
	GetKind(context.Context, ResourceStore_getKind) error
}

// ResourceStore_NewServer creates a new Server from an implementation of ResourceStore_Server.
func ResourceStore_NewServer(s ResourceStore_Server, policy *server.Policy) *server.Server {
	c, _ := s.(server.Shutdowner)
	return server.New(ResourceStore_Methods(nil, s), s, c, policy)
}

// ResourceStore_ServerToClient creates a new Client from an implementation of ResourceStore_Server.
// The caller is responsible for calling Release on the returned Client.
func ResourceStore_ServerToClient(s ResourceStore_Server, policy *server.Policy) ResourceStore {
	return ResourceStore{Client: capnp.NewClient(ResourceStore_NewServer(s, policy))}
}

// ResourceStore_Methods appends Methods to a slice that invoke the methods on s.
// This can be used to create a more complicated Server.
func ResourceStore_Methods(methods []server.Method, s ResourceStore_Server) []server.Method {
	if cap(methods) == 0 {
		methods = make([]server.Method, 0, 1)
	}

	methods = append(methods, server.Method{
		Method: capnp.Method{
			InterfaceID:   0x890d6d36373c01d5,
			MethodID:      0,
			InterfaceName: "protocol/resource-store.capnp:ResourceStore",
			MethodName:    "getKind",
		},
		Impl: func(ctx context.Context, call *server.Call) error {
			return s.GetKind(ctx, ResourceStore_getKind{call})
		},
	})

	return methods
}

// ResourceStore_getKind holds the state for a server call to ResourceStore.getKind.
// See server.Call for documentation.
type ResourceStore_getKind struct {
	*server.Call
}

// Args returns the call's arguments.
func (c ResourceStore_getKind) Args() ResourceStore_getKind_Params {
	return ResourceStore_getKind_Params{Struct: c.Call.Args()}
}

// AllocResults allocates the results struct.
func (c ResourceStore_getKind) AllocResults() (ResourceStore_getKind_Results, error) {
	r, err := c.Call.AllocResults(capnp.ObjectSize{DataSize: 0, PointerCount: 1})
	return ResourceStore_getKind_Results{Struct: r}, err
}

type ResourceStore_getKind_Params struct{ capnp.Struct }

// ResourceStore_getKind_Params_TypeID is the unique identifier for the type ResourceStore_getKind_Params.
const ResourceStore_getKind_Params_TypeID = 0xde742d397e618e85

func NewResourceStore_getKind_Params(s *capnp.Segment) (ResourceStore_getKind_Params, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1})
	return ResourceStore_getKind_Params{st}, err
}

func NewRootResourceStore_getKind_Params(s *capnp.Segment) (ResourceStore_getKind_Params, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1})
	return ResourceStore_getKind_Params{st}, err
}

func ReadRootResourceStore_getKind_Params(msg *capnp.Message) (ResourceStore_getKind_Params, error) {
	root, err := msg.Root()
	return ResourceStore_getKind_Params{root.Struct()}, err
}

func (s ResourceStore_getKind_Params) String() string {
	str, _ := text.Marshal(0xde742d397e618e85, s.Struct)
	return str
}

func (s ResourceStore_getKind_Params) Kind() (string, error) {
	p, err := s.Struct.Ptr(0)
	return p.Text(), err
}

func (s ResourceStore_getKind_Params) HasKind() bool {
	return s.Struct.HasPtr(0)
}

func (s ResourceStore_getKind_Params) KindBytes() ([]byte, error) {
	p, err := s.Struct.Ptr(0)
	return p.TextBytes(), err
}

func (s ResourceStore_getKind_Params) SetKind(v string) error {
	return s.Struct.SetText(0, v)
}

// ResourceStore_getKind_Params_List is a list of ResourceStore_getKind_Params.
type ResourceStore_getKind_Params_List struct{ capnp.List }

// NewResourceStore_getKind_Params creates a new list of ResourceStore_getKind_Params.
func NewResourceStore_getKind_Params_List(s *capnp.Segment, sz int32) (ResourceStore_getKind_Params_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1}, sz)
	return ResourceStore_getKind_Params_List{l}, err
}

func (s ResourceStore_getKind_Params_List) At(i int) ResourceStore_getKind_Params {
	return ResourceStore_getKind_Params{s.List.Struct(i)}
}

func (s ResourceStore_getKind_Params_List) Set(i int, v ResourceStore_getKind_Params) error {
	return s.List.SetStruct(i, v.Struct)
}

func (s ResourceStore_getKind_Params_List) String() string {
	str, _ := text.MarshalList(0xde742d397e618e85, s.List)
	return str
}

// ResourceStore_getKind_Params_Future is a wrapper for a ResourceStore_getKind_Params promised by a client call.
type ResourceStore_getKind_Params_Future struct{ *capnp.Future }

func (p ResourceStore_getKind_Params_Future) Struct() (ResourceStore_getKind_Params, error) {
	s, err := p.Future.Struct()
	return ResourceStore_getKind_Params{s}, err
}

type ResourceStore_getKind_Results struct{ capnp.Struct }

// ResourceStore_getKind_Results_TypeID is the unique identifier for the type ResourceStore_getKind_Results.
const ResourceStore_getKind_Results_TypeID = 0xcbcee9c30ec68bc2

func NewResourceStore_getKind_Results(s *capnp.Segment) (ResourceStore_getKind_Results, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1})
	return ResourceStore_getKind_Results{st}, err
}

func NewRootResourceStore_getKind_Results(s *capnp.Segment) (ResourceStore_getKind_Results, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1})
	return ResourceStore_getKind_Results{st}, err
}

func ReadRootResourceStore_getKind_Results(msg *capnp.Message) (ResourceStore_getKind_Results, error) {
	root, err := msg.Root()
	return ResourceStore_getKind_Results{root.Struct()}, err
}

func (s ResourceStore_getKind_Results) String() string {
	str, _ := text.Marshal(0xcbcee9c30ec68bc2, s.Struct)
	return str
}

func (s ResourceStore_getKind_Results) ResKind() ResourceKind {
	p, _ := s.Struct.Ptr(0)
	return ResourceKind{Client: p.Interface().Client()}
}

func (s ResourceStore_getKind_Results) HasResKind() bool {
	return s.Struct.HasPtr(0)
}

func (s ResourceStore_getKind_Results) SetResKind(v ResourceKind) error {
	if !v.Client.IsValid() {
		return s.Struct.SetPtr(0, capnp.Ptr{})
	}
	seg := s.Segment()
	in := capnp.NewInterface(seg, seg.Message().AddCap(v.Client))
	return s.Struct.SetPtr(0, in.ToPtr())
}

// ResourceStore_getKind_Results_List is a list of ResourceStore_getKind_Results.
type ResourceStore_getKind_Results_List struct{ capnp.List }

// NewResourceStore_getKind_Results creates a new list of ResourceStore_getKind_Results.
func NewResourceStore_getKind_Results_List(s *capnp.Segment, sz int32) (ResourceStore_getKind_Results_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1}, sz)
	return ResourceStore_getKind_Results_List{l}, err
}

func (s ResourceStore_getKind_Results_List) At(i int) ResourceStore_getKind_Results {
	return ResourceStore_getKind_Results{s.List.Struct(i)}
}

func (s ResourceStore_getKind_Results_List) Set(i int, v ResourceStore_getKind_Results) error {
	return s.List.SetStruct(i, v.Struct)
}

func (s ResourceStore_getKind_Results_List) String() string {
	str, _ := text.MarshalList(0xcbcee9c30ec68bc2, s.List)
	return str
}

// ResourceStore_getKind_Results_Future is a wrapper for a ResourceStore_getKind_Results promised by a client call.
type ResourceStore_getKind_Results_Future struct{ *capnp.Future }

func (p ResourceStore_getKind_Results_Future) Struct() (ResourceStore_getKind_Results, error) {
	s, err := p.Future.Struct()
	return ResourceStore_getKind_Results{s}, err
}

func (p ResourceStore_getKind_Results_Future) ResKind() ResourceKind {
	return ResourceKind{Client: p.Future.Field(0, nil).Client()}
}

const schema_91b9cce5437dcbad = "x\xda\xbcT\xcfk$E\x18\xfd^Uu:Bv" +
	"g*\x1d\x19rp\xf7\xe0,\xb2\xd1Yw\xcd\xa2\x18" +
	"\x84\x99\xd9\x1f\xb8\xa2\xb2S3\xebF\xe2\x0f\xe8t\x8a" +
	"\x90d23t\xf7x\xd3\x9c\x82\x04A\xf0\xa0\xe0?" +
	"\xe0ED\xc1\x83z\xf0\xe2O$FP\x88\x90\x089" +
	"Ds\xd0?\xc1KIM\xa6g:c4\x19\x04o" +
	"\xcd\xeb\xaa\xf7\xbd\xef{\xef\xab\xcb[(\xb1+\xce\x9a" +
	" RW\x9d\x11\xb3\xf9\\ \xaf\x8aw\xd6I>\x08" +
	"\"\xe1f1}\x81\xed\x83\x84\xd9\xc6\x13\x8f=\xbaz" +
	"f\x83\xe49n>\xd8|\xf5\xfa\xc1\xf7\x9f\xbdE\x84" +
	"\xe9I6\x0f\xaf\xc0\\\"\xef\"{\xd2\xf3\xed\x97)" +
	"|\xfb\xd1\xfd\x07&\xff\xfe!\x8f\x03K\xf4\x14\xfb\x13" +
	"\x04\xef%V$\x98\xeb\xfb\xfcVK\x7f\xfc\x09\xc9s" +
	"\xe8\xd39\xdc\x1e\xfc\x9a-\xc3\xdb\xe90n\xb3\x0f\x89" +
	"\xbc\x0d\x9e3_\xbc\xf1\xcd\xd9/\x7f\xffa\x93\xe4C" +
	"=\xc6u\xbeo\x19\xdf\xe5E\"oR\xe4\xcc\xa7/" +
	"\xff\xf6\xc2\xec/+?\x0f\x88\xa4,\xa6\xef\x15s\xf0" +
	".\x0aKzA\xbc\xeem\x09\xd7\xdb\x129\xf3\xf6}" +
	"{wG~\xda\xd9M5\xfc\x9d`\x8c\x84Y\x7f\xd3" +
	"\x7f\xed\xf1B\xbc\x97.\xf8\xb9\xd8\xb5\x05\x7f\x14\xb6\xe0" +
	"=N\xcel\xe4\x7f]\x99\xfd\xea=\x93\xee\xd3q\xfe" +
	"\xb0\x87&\x9d\"\x15L+l\xc6\xcd\xa0Y\x1fy8" +
	"\xd4Q\xb3\x1d\x06\xba\x10\xc5\xcdP_\x0a\xfcV\xa35" +
	"S\xed\x82O/5\x16.-\xea\xf8\xf6\xfc\xb2\x0e\xe2" +
	"|\xc5\x0f]\x7f5\xea\xdd\x16\xff~\xbb\x16\xbb\xcdP" +
	"W\x00%\xb8C\xd4\x93\x8edhR^#&\x9d\xdc" +
	"\xda\xa2\x8em\xa9\xf2(\xa43%\x9d\x99L\xad\xa5\x83" +
	"b-\xf6\xe3vT\x01\x86\x92\x1b\x84\xda\x8fuWq" +
	"\xb1\xe2\x87\xfej\xa4\x04\x17D\x02D\xf2\xcc#Dj" +
	"\x94C\xbd\xc8p\xfe\x15\xbf\xde\xd6\xc8\xf6m'*A" +
	"\xe2\xbc\x12\x0ciP\xe2\x015\x0a\x00\xf6&\xa0\xb2\x1c" +
	"\x18\x07\xfa\xc6\x12a\xdc\x19\x00\xb2\x84\xd3N\xea\xf6|" +
	"\xc6\xca\xb5\xa3\x1a\xeb)\xbd9G\xa4np\xa8\x0a\x83" +
	"\x04&`\xc1g\xa7\x88\xd4-\x0eu\x87A26\x01" +
	"F$\xd5\x0c\x91z\x86C=\xcf`\xfc\xd6\xd2]\x1d" +
	"FK\xc4\x9b\x0d\x8c\x11\xc3\x18!\x13\xb5t\xd0Q\x9c" +
	"j\x0a\xe3\x84b\xd4\x99\xf1\xa1\xf8\x81\x7f\xc7\xbaqZ" +
	"+j\x1d\xac\xebk\xbe\xaa\xa3\xb6[\x8f\x8f\xf8p\xad" +
	"\xef\xc3Z\xa8#{\x0e2=\xc0\xbe\x13)\xf0\x9f\x9c" +
	"\xe8\xeda\xe2D\x1a\x90'5#N\xca\x15o,T" +
	":5m\x8e\x93\xd7\x08\xc9\x9a\xc9+U\xa2\xf2e\x94" +
	"K\x90\xca\x05z\xef\x0c\x92=\x967\x97\x89\xca7P" +
	"\xbe\x03\xa9]\x93\xac\x14!\xfe[\x8f\x1d\x9b\x8f\x03K" +
	"0I\xb6\xa9\x13\x97a\xaeVp\xc2\x08\xce\x0e\xbbZ" +
	"\xd6\xd3z\x1cQB0L\x1e\xecV\xf2\xa3k9\xd5" +
	"\x8d\xc3\x04Cf\xc5f\xa1\x1b\xdd\xff\x94\xc2\x81\xf7\xab" +
	"\xaa\xa3L{ \x86\xff\xe7s\xf0W\x00\x00\x00\xff\xff" +
	"Q\x07\xfe\x9c"

func init() {
	schemas.Register(schema_91b9cce5437dcbad,
		0x85960434116355cb,
		0x890d6d36373c01d5,
		0xab24ffe523b0c72d,
		0xb7b365704803e243,
		0xcbcee9c30ec68bc2,
		0xd66bdb575be45eb8,
		0xdad9d20656de1d95,
		0xde742d397e618e85,
		0xffa6c4576be32489)
}
