apiVersion: core.meshx.co/v1
kind: IDL
metadata:
  name: directory-idl
spec:
  import: root/test-space/directory-idl
  namespace: com.meshx
  rootTable: Greeting

  attributes:
    priority: true
  
  unions:
    All:
      values:
        Red: string
        Green: string
        Blue: string
    
  enums:
    Color:
      doc: doc here
      attributes:
      values:
        Red: string
        Green: string
        Blue: string
  
  tables:
    TypeMeta:
      # doc: This is a table
      fields:
        apiVersion:
          type: string
          attributes:
            required: true
        kind:
          type: string
          attributes:
            required: true
    
    ObjectMeta:
      # doc: This is a table
      fields:
        name:
          type: string
          attributes:
            required: true
        space:
          type: string
          attributes:
            required: true

    GreetingResource:
      extends: TypeMeta
      doc: This is a table
      fields:
        message:
          type: string
          attributes:
            required: true

  capabilities:
    Directory:
      doc: A directory interface
      attributes:
      calls:
        
        create:
          doc: Creates a file.
          attributes:
          params:
            name:
              type: string
          results:
            file:
              type: File

        open:
          doc: Opens a file.
          attributes:
          params:
            name:
              type: string
          results:
            file:
              type: File

        remove:
          doc: Remove a file.
          attributes:
          params:
            name:
              type: Text
