[package]
name = "fiber_kernel"
version = "0.1.0"
edition = "2021"
crate-type = ["cdylib"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fiber_sys = {version = "0.1.0", path = "../fiber_sys"}