[package]
name = "meshx_plugins"
authors.workspace = true
categories = ["wasm"]
edition = "2024"
license.workspace = true
repository.workspace = true
version.workspace = true

[lib]
path = "src/lib.rs"

[features]
default = ["wasi-logging"]
wasi-logging = []

[dependencies]
tokio = {workspace = true, features = ["full"]}
wasmtime = {workspace = true}
anyhow = {workspace = true}
tracing = {workspace = true}
wash-runtime = {workspace = true}
async-trait = {workspace = true}