// WARNING: This file is machine generated by midlgen.

// midl_experiment = no_optional_structs
// midl_experiment = output_index_json
// midl_experiment = simple_empty_response_syntax
// midl_experiment = unknown_interactions

#![allow(
    unused_parens, // one-element-tuple-case is not a tuple
    unused_mut, // not all args require mutation, but many do
    nonstandard_style, // auto-caps does its best, but is not always successful
)]
#![recursion_limit = "512"]

#[allow(unused_imports)]
use fiber_rust as fx;

#[allow(unused_imports)]
use {
    bitflags::bitflags,
    fiber_status as fx_status,
    futures::future::{self, MaybeDone, TryFutureExt},
    midl::{
        client::QueryResponseFut,
        encoding::zerocopy,
        endpoints::{ControlHandle as _, Responder as _},
        midl_bits, midl_enum, midl_struct, midl_table, midl_union,
    },
};

const _MIDL_TRACE_BINDINGS_RUST: u32 = 6;

#[derive(Debug, Eq, PartialEq, Ord, PartialOrd, Hash)]
pub struct ParentGetChildRequestResponse {
    pub r: midl::endpoints::ServerEnd<ChildMarker>,
}
impl midl::encoding::Standalone for ParentGetChildRequestResponse {}
midl_struct! {
    name: ParentGetChildRequestResponse,
    resource: true,
    members: [
        r {
            ty: midl::encoding::Endpoint<midl::endpoints::ServerEnd<ChildMarker>>,
            resource: true,
            index: 0,
            typevar: T0,
            offset_v1: 0,
            offset_v2: 0,
        },
    ],
    padding_v1: [
    ],
    padding_v2: [
    ],
    size_v1: 4,
    size_v2: 4,
    align_v1: 4,
    align_v2: 4,
}
#[derive(Debug, Eq, PartialEq, Ord, PartialOrd, Hash)]
pub struct ParentGetChildResponse {
    pub c: midl::endpoints::ClientEnd<ChildMarker>,
}
impl midl::encoding::Standalone for ParentGetChildResponse {}
midl_struct! {
    name: ParentGetChildResponse,
    resource: true,
    members: [
        c {
            ty: midl::encoding::Endpoint<midl::endpoints::ClientEnd<ChildMarker>>,
            resource: true,
            index: 0,
            typevar: T0,
            offset_v1: 0,
            offset_v2: 0,
        },
    ],
    padding_v1: [
    ],
    padding_v2: [
    ],
    size_v1: 4,
    size_v2: 4,
    align_v1: 4,
    align_v2: 4,
}
#[derive(Debug, Eq, PartialEq, Ord, PartialOrd, Hash)]
pub struct ParentTakeChildRequest {
    pub c: midl::endpoints::ClientEnd<ChildMarker>,
}
impl midl::encoding::Standalone for ParentTakeChildRequest {}
midl_struct! {
    name: ParentTakeChildRequest,
    resource: true,
    members: [
        c {
            ty: midl::encoding::Endpoint<midl::endpoints::ClientEnd<ChildMarker>>,
            resource: true,
            index: 0,
            typevar: T0,
            offset_v1: 0,
            offset_v2: 0,
        },
    ],
    padding_v1: [
    ],
    padding_v2: [
    ],
    size_v1: 4,
    size_v2: 4,
    align_v1: 4,
    align_v2: 4,
}
#[derive(Debug, Eq, PartialEq, Ord, PartialOrd, Hash)]
pub struct ParentTakeChildRequestRequest {
    pub r: midl::endpoints::ServerEnd<ChildMarker>,
}
impl midl::encoding::Standalone for ParentTakeChildRequestRequest {}
midl_struct! {
    name: ParentTakeChildRequestRequest,
    resource: true,
    members: [
        r {
            ty: midl::encoding::Endpoint<midl::endpoints::ServerEnd<ChildMarker>>,
            resource: true,
            index: 0,
            typevar: T0,
            offset_v1: 0,
            offset_v2: 0,
        },
    ],
    padding_v1: [
    ],
    padding_v2: [
    ],
    size_v1: 4,
    size_v2: 4,
    align_v1: 4,
    align_v2: 4,
}
#[derive(Debug, Copy, Clone, Eq, PartialEq, Ord, PartialOrd, Hash)]
pub struct ChildMarker;
impl midl::endpoints::ProtocolMarker for ChildMarker {
    type Proxy = ChildProxy;
    type RequestStream = ChildRequestStream;
    const DEBUG_NAME: &'static str = "(anonymous) Child";
}
pub trait ChildProxyInterface: Send + Sync {}
#[derive(Debug)]
#[cfg(target_os = "fuchsia")]
pub struct ChildSynchronousProxy {
    client: midl::client::sync::Client,
}
#[cfg(target_os = "fuchsia")]
impl ChildSynchronousProxy {
    pub fn new(channel: midl::Channel) -> Self {
        let protocol_name = <ChildMarker as midl::endpoints::ProtocolMarker>::DEBUG_NAME;
        Self {
            client: midl::client::sync::Client::new(channel, protocol_name),
        }
    }
    pub fn into_channel(self) -> midl::Channel {
        self.client.into_channel()
    }
    /// Waits until an event arrives and returns it. It is safe for other
    /// threads to make concurrent requests while waiting for an event.
    pub fn wait_for_event(&self, deadline: zx::Time) -> Result<ChildEvent, midl::Error> {
        ChildEvent::decode(self.client.wait_for_event(deadline)?)
    }
}
#[derive(Debug, Clone)]
pub struct ChildProxy {
    client: midl::client::Client,
}
impl midl::endpoints::Proxy for ChildProxy {
    type Protocol = ChildMarker;
    fn from_channel(inner: midl::AsyncChannel) -> Self {
        Self::new(inner)
    }
    fn into_channel(self) -> Result<::midl::AsyncChannel, Self> {
        self.client.into_channel().map_err(|client| Self { client })
    }
    fn as_channel(&self) -> &::midl::AsyncChannel {
        self.client.as_channel()
    }
}
impl ChildProxy {
    /// Create a new Proxy for Child
    pub fn new(channel: midl::AsyncChannel) -> Self {
        let protocol_name = <ChildMarker as midl::endpoints::ProtocolMarker>::DEBUG_NAME;
        Self {
            client: midl::client::Client::new(channel, protocol_name),
        }
    }
    /// Get a Stream of events from the remote end of the Child protocol
    ///
    /// # Panics
    ///
    /// Panics if the event stream was already taken.
    pub fn take_event_stream(&self) -> ChildEventStream {
        ChildEventStream {
            event_receiver: self.client.take_event_receiver(),
        }
    }
}
impl ChildProxyInterface for ChildProxy {}
pub struct ChildEventStream {
    event_receiver: midl::client::EventReceiver,
}
impl std::marker::Unpin for ChildEventStream {}
impl futures::stream::FusedStream for ChildEventStream {
    fn is_terminated(&self) -> bool {
        self.event_receiver.is_terminated()
    }
}
impl futures::Stream for ChildEventStream {
    type Item = Result<ChildEvent, midl::Error>;
    fn poll_next(
        mut self: std::pin::Pin<&mut Self>,
        cx: &mut std::task::Context<'_>,
    ) -> std::task::Poll<Option<Self::Item>> {
        let buf = match futures::ready!(futures::stream::StreamExt::poll_next_unpin(
            &mut self.event_receiver,
            cx
        )?) {
            Some(buf) => buf,
            None => return std::task::Poll::Ready(None),
        };
        std::task::Poll::Ready(Some(ChildEvent::decode(buf)))
    }
}
#[derive(Debug)]
pub enum ChildEvent {}
impl ChildEvent {
    /// Decodes a message buffer as a [`ChildEvent`]. Transaction
    /// ID in the message must be zero; this method does not check TXID.
    fn decode(mut buf: midl::MessageBufEtc) -> Result<ChildEvent, midl::Error> {
        let (bytes, _handles) = buf.split_mut();
        let (tx_header, _body_bytes) = midl::encoding::decode_transaction_header(bytes)?;
        match tx_header.ordinal() {
            _ => Err(midl::Error::UnknownOrdinal {
                ordinal: tx_header.ordinal(),
                protocol_name: <ChildMarker as midl::endpoints::ProtocolMarker>::DEBUG_NAME,
            }),
        }
    }
}
/// A Stream of incoming requests for Child
pub struct ChildRequestStream {
    inner: std::sync::Arc<midl::ServeInner>,
    is_terminated: bool,
}
impl std::marker::Unpin for ChildRequestStream {}
impl futures::stream::FusedStream for ChildRequestStream {
    fn is_terminated(&self) -> bool {
        self.is_terminated
    }
}
impl midl::endpoints::RequestStream for ChildRequestStream {
    type Protocol = ChildMarker;
    type ControlHandle = ChildControlHandle;
    fn from_channel(channel: midl::AsyncChannel) -> Self {
        Self {
            inner: std::sync::Arc::new(midl::ServeInner::new(channel)),
            is_terminated: false,
        }
    }
    fn control_handle(&self) -> Self::ControlHandle {
        ChildControlHandle {
            inner: self.inner.clone(),
        }
    }
    fn into_inner(self) -> (::std::sync::Arc<midl::ServeInner>, bool) {
        (self.inner, self.is_terminated)
    }
    fn from_inner(inner: std::sync::Arc<midl::ServeInner>, is_terminated: bool) -> Self {
        Self { inner, is_terminated }
    }
}
impl futures::Stream for ChildRequestStream {
    type Item = Result<ChildRequest, midl::Error>;
    fn poll_next(
        mut self: std::pin::Pin<&mut Self>,
        cx: &mut std::task::Context<'_>,
    ) -> std::task::Poll<Option<Self::Item>> {
        let this = &mut *self;
        if this.inner.poll_shutdown(cx) {
            this.is_terminated = true;
            return std::task::Poll::Ready(None);
        }
        if this.is_terminated {
            panic!("polled ChildRequestStream after completion");
        }
        midl::encoding::with_tls_decode_buf(|bytes, handles| {
            match this.inner.channel().read_etc(cx, bytes, handles) {
                std::task::Poll::Ready(Ok(())) => {}
                std::task::Poll::Pending => return std::task::Poll::Pending,
                std::task::Poll::Ready(Err(fx_status::Status::PEER_CLOSED)) => {
                    this.is_terminated = true;
                    return std::task::Poll::Ready(None);
                }
                std::task::Poll::Ready(Err(e)) => {
                    return std::task::Poll::Ready(Some(Err(midl::Error::ServerRequestRead(e))))
                }
            }
            // A message has been received from the channel
            let (header, _body_bytes) = midl::encoding::decode_transaction_header(bytes)?;
            if !header.is_compatible() {
                return std::task::Poll::Ready(Some(Err(midl::Error::IncompatibleMagicNumber(header.magic_number()))));
            }
            std::task::Poll::Ready(Some(match header.ordinal() {
                _ => Err(midl::Error::UnknownOrdinal {
                    ordinal: header.ordinal(),
                    protocol_name: <ChildMarker as midl::endpoints::ProtocolMarker>::DEBUG_NAME,
                }),
            }))
        })
    }
}
#[derive(Debug)]
pub enum ChildRequest {}
impl ChildRequest {
    /// Name of the method defined in midl
    pub fn method_name(&self) -> &'static str {
        match *self {}
    }
}
#[derive(Debug, Clone)]
pub struct ChildControlHandle {
    inner: std::sync::Arc<midl::ServeInner>,
}
impl midl::endpoints::ControlHandle for ChildControlHandle {
    fn shutdown(&self) {
        self.inner.shutdown()
    }
    fn shutdown_with_epitaph(&self, status: fx_status::Status) {
        self.inner.shutdown_with_epitaph(status)
    }
    fn is_closed(&self) -> bool {
        self.inner.channel().is_closed()
    }
    fn on_closed<'a>(&'a self) -> midl::OnSignals<'a> {
        self.inner.channel().on_closed()
    }
}
impl ChildControlHandle {}
#[derive(Debug, Copy, Clone, Eq, PartialEq, Ord, PartialOrd, Hash)]
pub struct ParentMarker;
impl midl::endpoints::ProtocolMarker for ParentMarker {
    type Proxy = ParentProxy;
    type RequestStream = ParentRequestStream;
    const DEBUG_NAME: &'static str = "(anonymous) Parent";
}
pub trait ParentProxyInterface: Send + Sync {
    type GetChildResponseFut: std::future::Future<Output = Result<midl::endpoints::ClientEnd<ChildMarker>, midl::Error>>
        + Send;
    fn r#get_child(&self) -> Self::GetChildResponseFut;
    type GetChildRequestResponseFut: std::future::Future<Output = Result<midl::endpoints::ServerEnd<ChildMarker>, midl::Error>>
        + Send;
    fn r#get_child_request(&self) -> Self::GetChildRequestResponseFut;
    fn r#take_child(&self, c: midl::endpoints::ClientEnd<ChildMarker>) -> Result<(), midl::Error>;
    fn r#take_child_request(&self, r: midl::endpoints::ServerEnd<ChildMarker>) -> Result<(), midl::Error>;
}
#[derive(Debug)]
#[cfg(target_os = "fuchsia")]
pub struct ParentSynchronousProxy {
    client: midl::client::sync::Client,
}
#[cfg(target_os = "fuchsia")]
impl ParentSynchronousProxy {
    pub fn new(channel: midl::Channel) -> Self {
        let protocol_name = <ParentMarker as midl::endpoints::ProtocolMarker>::DEBUG_NAME;
        Self {
            client: midl::client::sync::Client::new(channel, protocol_name),
        }
    }
    pub fn into_channel(self) -> midl::Channel {
        self.client.into_channel()
    }
    /// Waits until an event arrives and returns it. It is safe for other
    /// threads to make concurrent requests while waiting for an event.
    pub fn wait_for_event(&self, deadline: zx::Time) -> Result<ParentEvent, midl::Error> {
        ParentEvent::decode(self.client.wait_for_event(deadline)?)
    }
    pub fn r#get_child(&self, ___deadline: zx::Time) -> Result<midl::endpoints::ClientEnd<ChildMarker>, midl::Error> {
        let _response = self
            .client
            .send_query::<midl::encoding::EmptyPayload, ParentGetChildResponse, false, false>(
                (),
                0xc3cd963aafc873b,
                midl::encoding::DynamicFlags::empty(),
                ___deadline,
            )?;
        Ok(_response.c)
    }
    pub fn r#get_child_request(
        &self,
        ___deadline: zx::Time,
    ) -> Result<midl::endpoints::ServerEnd<ChildMarker>, midl::Error> {
        let _response = self
            .client
            .send_query::<midl::encoding::EmptyPayload, ParentGetChildRequestResponse, false, false>(
                (),
                0xf38d08d64f71c79,
                midl::encoding::DynamicFlags::empty(),
                ___deadline,
            )?;
        Ok(_response.r)
    }
    pub fn r#take_child(&self, mut c: midl::endpoints::ClientEnd<ChildMarker>) -> Result<(), midl::Error> {
        self.client.send::<ParentTakeChildRequest, false>(
            (c,),
            0x3e08fd7ca04b2290,
            midl::encoding::DynamicFlags::empty(),
        )
    }
    pub fn r#take_child_request(&self, mut r: midl::endpoints::ServerEnd<ChildMarker>) -> Result<(), midl::Error> {
        self.client.send::<ParentTakeChildRequestRequest, false>(
            (r,),
            0x2063f76b1bb45f87,
            midl::encoding::DynamicFlags::empty(),
        )
    }
}
#[derive(Debug, Clone)]
pub struct ParentProxy {
    client: midl::client::Client,
}
impl midl::endpoints::Proxy for ParentProxy {
    type Protocol = ParentMarker;
    fn from_channel(inner: midl::AsyncChannel) -> Self {
        Self::new(inner)
    }
    fn into_channel(self) -> Result<::midl::AsyncChannel, Self> {
        self.client.into_channel().map_err(|client| Self { client })
    }
    fn as_channel(&self) -> &::midl::AsyncChannel {
        self.client.as_channel()
    }
}
impl ParentProxy {
    /// Create a new Proxy for Parent
    pub fn new(channel: midl::AsyncChannel) -> Self {
        let protocol_name = <ParentMarker as midl::endpoints::ProtocolMarker>::DEBUG_NAME;
        Self {
            client: midl::client::Client::new(channel, protocol_name),
        }
    }
    /// Get a Stream of events from the remote end of the Parent protocol
    ///
    /// # Panics
    ///
    /// Panics if the event stream was already taken.
    pub fn take_event_stream(&self) -> ParentEventStream {
        ParentEventStream {
            event_receiver: self.client.take_event_receiver(),
        }
    }
    pub fn r#get_child(&self) -> midl::client::QueryResponseFut<midl::endpoints::ClientEnd<ChildMarker>> {
        ParentProxyInterface::r#get_child(self)
    }
    pub fn r#get_child_request(&self) -> midl::client::QueryResponseFut<midl::endpoints::ServerEnd<ChildMarker>> {
        ParentProxyInterface::r#get_child_request(self)
    }
    pub fn r#take_child(&self, mut c: midl::endpoints::ClientEnd<ChildMarker>) -> Result<(), midl::Error> {
        ParentProxyInterface::r#take_child(self, c)
    }
    pub fn r#take_child_request(&self, mut r: midl::endpoints::ServerEnd<ChildMarker>) -> Result<(), midl::Error> {
        ParentProxyInterface::r#take_child_request(self, r)
    }
}
impl ParentProxyInterface for ParentProxy {
    type GetChildResponseFut = midl::client::QueryResponseFut<midl::endpoints::ClientEnd<ChildMarker>>;
    fn r#get_child(&self) -> Self::GetChildResponseFut {
        fn _decode(
            mut _buf: Result<midl::MessageBufEtc, midl::Error>,
        ) -> Result<midl::endpoints::ClientEnd<ChildMarker>, midl::Error> {
            let _response = midl::client::decode_transaction_body::<ParentGetChildResponse, false>(_buf?)?;
            Ok(_response.c)
        }
        self.client
            .send_query_and_decode::<midl::encoding::EmptyPayload, midl::endpoints::ClientEnd<ChildMarker>, false>(
                (),
                0xc3cd963aafc873b,
                midl::encoding::DynamicFlags::empty(),
                _decode,
            )
    }
    type GetChildRequestResponseFut = midl::client::QueryResponseFut<midl::endpoints::ServerEnd<ChildMarker>>;
    fn r#get_child_request(&self) -> Self::GetChildRequestResponseFut {
        fn _decode(
            mut _buf: Result<midl::MessageBufEtc, midl::Error>,
        ) -> Result<midl::endpoints::ServerEnd<ChildMarker>, midl::Error> {
            let _response = midl::client::decode_transaction_body::<ParentGetChildRequestResponse, false>(_buf?)?;
            Ok(_response.r)
        }
        self.client
            .send_query_and_decode::<midl::encoding::EmptyPayload, midl::endpoints::ServerEnd<ChildMarker>, false>(
                (),
                0xf38d08d64f71c79,
                midl::encoding::DynamicFlags::empty(),
                _decode,
            )
    }
    fn r#take_child(&self, mut c: midl::endpoints::ClientEnd<ChildMarker>) -> Result<(), midl::Error> {
        self.client.send::<ParentTakeChildRequest, false>(
            (c,),
            0x3e08fd7ca04b2290,
            midl::encoding::DynamicFlags::empty(),
        )
    }
    fn r#take_child_request(&self, mut r: midl::endpoints::ServerEnd<ChildMarker>) -> Result<(), midl::Error> {
        self.client.send::<ParentTakeChildRequestRequest, false>(
            (r,),
            0x2063f76b1bb45f87,
            midl::encoding::DynamicFlags::empty(),
        )
    }
}
pub struct ParentEventStream {
    event_receiver: midl::client::EventReceiver,
}
impl std::marker::Unpin for ParentEventStream {}
impl futures::stream::FusedStream for ParentEventStream {
    fn is_terminated(&self) -> bool {
        self.event_receiver.is_terminated()
    }
}
impl futures::Stream for ParentEventStream {
    type Item = Result<ParentEvent, midl::Error>;
    fn poll_next(
        mut self: std::pin::Pin<&mut Self>,
        cx: &mut std::task::Context<'_>,
    ) -> std::task::Poll<Option<Self::Item>> {
        let buf = match futures::ready!(futures::stream::StreamExt::poll_next_unpin(
            &mut self.event_receiver,
            cx
        )?) {
            Some(buf) => buf,
            None => return std::task::Poll::Ready(None),
        };
        std::task::Poll::Ready(Some(ParentEvent::decode(buf)))
    }
}
#[derive(Debug)]
pub enum ParentEvent {}
impl ParentEvent {
    /// Decodes a message buffer as a [`ParentEvent`]. Transaction
    /// ID in the message must be zero; this method does not check TXID.
    fn decode(mut buf: midl::MessageBufEtc) -> Result<ParentEvent, midl::Error> {
        let (bytes, _handles) = buf.split_mut();
        let (tx_header, _body_bytes) = midl::encoding::decode_transaction_header(bytes)?;
        match tx_header.ordinal() {
            _ => Err(midl::Error::UnknownOrdinal {
                ordinal: tx_header.ordinal(),
                protocol_name: <ParentMarker as midl::endpoints::ProtocolMarker>::DEBUG_NAME,
            }),
        }
    }
}
/// A Stream of incoming requests for Parent
pub struct ParentRequestStream {
    inner: std::sync::Arc<midl::ServeInner>,
    is_terminated: bool,
}
impl std::marker::Unpin for ParentRequestStream {}
impl futures::stream::FusedStream for ParentRequestStream {
    fn is_terminated(&self) -> bool {
        self.is_terminated
    }
}
impl midl::endpoints::RequestStream for ParentRequestStream {
    type Protocol = ParentMarker;
    type ControlHandle = ParentControlHandle;
    fn from_channel(channel: midl::AsyncChannel) -> Self {
        Self {
            inner: std::sync::Arc::new(midl::ServeInner::new(channel)),
            is_terminated: false,
        }
    }
    fn control_handle(&self) -> Self::ControlHandle {
        ParentControlHandle {
            inner: self.inner.clone(),
        }
    }
    fn into_inner(self) -> (::std::sync::Arc<midl::ServeInner>, bool) {
        (self.inner, self.is_terminated)
    }
    fn from_inner(inner: std::sync::Arc<midl::ServeInner>, is_terminated: bool) -> Self {
        Self { inner, is_terminated }
    }
}
impl futures::Stream for ParentRequestStream {
    type Item = Result<ParentRequest, midl::Error>;
    fn poll_next(
        mut self: std::pin::Pin<&mut Self>,
        cx: &mut std::task::Context<'_>,
    ) -> std::task::Poll<Option<Self::Item>> {
        let this = &mut *self;
        if this.inner.poll_shutdown(cx) {
            this.is_terminated = true;
            return std::task::Poll::Ready(None);
        }
        if this.is_terminated {
            panic!("polled ParentRequestStream after completion");
        }
        midl::encoding::with_tls_decode_buf(|bytes, handles| {
            match this.inner.channel().read_etc(cx, bytes, handles) {
                std::task::Poll::Ready(Ok(())) => {}
                std::task::Poll::Pending => return std::task::Poll::Pending,
                std::task::Poll::Ready(Err(fx_status::Status::PEER_CLOSED)) => {
                    this.is_terminated = true;
                    return std::task::Poll::Ready(None);
                }
                std::task::Poll::Ready(Err(e)) => {
                    return std::task::Poll::Ready(Some(Err(midl::Error::ServerRequestRead(e))))
                }
            }
            // A message has been received from the channel
            let (header, _body_bytes) = midl::encoding::decode_transaction_header(bytes)?;
            if !header.is_compatible() {
                return std::task::Poll::Ready(Some(Err(midl::Error::IncompatibleMagicNumber(header.magic_number()))));
            }
            std::task::Poll::Ready(Some(match header.ordinal() {
                0xc3cd963aafc873b => {
                    let mut req = midl::new_empty!(midl::encoding::EmptyPayload);
                    if header
                        .dynamic_flags()
                        .contains(midl::encoding::DynamicFlags::BYTE_OVERFLOW)
                    {
                        Err(midl::Error::LargeMessageImpossible)?;
                    }
                    midl::encoding::Decoder::decode_into::<midl::encoding::EmptyPayload>(
                        &header,
                        _body_bytes,
                        handles,
                        &mut req,
                    )?;
                    let control_handle = ParentControlHandle {
                        inner: this.inner.clone(),
                    };
                    Ok(ParentRequest::GetChild {
                        responder: ParentGetChildResponder {
                            control_handle: std::mem::ManuallyDrop::new(control_handle),
                            tx_id: header.tx_id(),
                            ordinal: header.ordinal(),
                        },
                    })
                }
                0xf38d08d64f71c79 => {
                    let mut req = midl::new_empty!(midl::encoding::EmptyPayload);
                    if header
                        .dynamic_flags()
                        .contains(midl::encoding::DynamicFlags::BYTE_OVERFLOW)
                    {
                        Err(midl::Error::LargeMessageImpossible)?;
                    }
                    midl::encoding::Decoder::decode_into::<midl::encoding::EmptyPayload>(
                        &header,
                        _body_bytes,
                        handles,
                        &mut req,
                    )?;
                    let control_handle = ParentControlHandle {
                        inner: this.inner.clone(),
                    };
                    Ok(ParentRequest::GetChildRequest {
                        responder: ParentGetChildRequestResponder {
                            control_handle: std::mem::ManuallyDrop::new(control_handle),
                            tx_id: header.tx_id(),
                            ordinal: header.ordinal(),
                        },
                    })
                }
                0x3e08fd7ca04b2290 => {
                    let mut req = midl::new_empty!(ParentTakeChildRequest);
                    if header
                        .dynamic_flags()
                        .contains(midl::encoding::DynamicFlags::BYTE_OVERFLOW)
                    {
                        Err(midl::Error::LargeMessageImpossible)?;
                    }
                    midl::encoding::Decoder::decode_into::<ParentTakeChildRequest>(
                        &header,
                        _body_bytes,
                        handles,
                        &mut req,
                    )?;
                    let control_handle = ParentControlHandle {
                        inner: this.inner.clone(),
                    };
                    Ok(ParentRequest::TakeChild {
                        c: req.c,
                        control_handle,
                    })
                }
                0x2063f76b1bb45f87 => {
                    let mut req = midl::new_empty!(ParentTakeChildRequestRequest);
                    if header
                        .dynamic_flags()
                        .contains(midl::encoding::DynamicFlags::BYTE_OVERFLOW)
                    {
                        Err(midl::Error::LargeMessageImpossible)?;
                    }
                    midl::encoding::Decoder::decode_into::<ParentTakeChildRequestRequest>(
                        &header,
                        _body_bytes,
                        handles,
                        &mut req,
                    )?;
                    let control_handle = ParentControlHandle {
                        inner: this.inner.clone(),
                    };
                    Ok(ParentRequest::TakeChildRequest {
                        r: req.r,
                        control_handle,
                    })
                }
                _ => Err(midl::Error::UnknownOrdinal {
                    ordinal: header.ordinal(),
                    protocol_name: <ParentMarker as midl::endpoints::ProtocolMarker>::DEBUG_NAME,
                }),
            }))
        })
    }
}
#[derive(Debug)]
pub enum ParentRequest {
    GetChild {
        responder: ParentGetChildResponder,
    },
    GetChildRequest {
        responder: ParentGetChildRequestResponder,
    },
    TakeChild {
        c: midl::endpoints::ClientEnd<ChildMarker>,
        control_handle: ParentControlHandle,
    },
    TakeChildRequest {
        r: midl::endpoints::ServerEnd<ChildMarker>,
        control_handle: ParentControlHandle,
    },
}
impl ParentRequest {
    #[allow(irrefutable_let_patterns)]
    pub fn into_get_child(self) -> Option<(ParentGetChildResponder)> {
        if let ParentRequest::GetChild { responder } = self {
            Some((responder))
        } else {
            None
        }
    }
    #[allow(irrefutable_let_patterns)]
    pub fn into_get_child_request(self) -> Option<(ParentGetChildRequestResponder)> {
        if let ParentRequest::GetChildRequest { responder } = self {
            Some((responder))
        } else {
            None
        }
    }
    #[allow(irrefutable_let_patterns)]
    pub fn into_take_child(self) -> Option<(midl::endpoints::ClientEnd<ChildMarker>, ParentControlHandle)> {
        if let ParentRequest::TakeChild { c, control_handle } = self {
            Some((c, control_handle))
        } else {
            None
        }
    }
    #[allow(irrefutable_let_patterns)]
    pub fn into_take_child_request(self) -> Option<(midl::endpoints::ServerEnd<ChildMarker>, ParentControlHandle)> {
        if let ParentRequest::TakeChildRequest { r, control_handle } = self {
            Some((r, control_handle))
        } else {
            None
        }
    }
    /// Name of the method defined in midl
    pub fn method_name(&self) -> &'static str {
        match *self {
            ParentRequest::GetChild { .. } => "get_child",
            ParentRequest::GetChildRequest { .. } => "get_child_request",
            ParentRequest::TakeChild { .. } => "take_child",
            ParentRequest::TakeChildRequest { .. } => "take_child_request",
        }
    }
}
#[derive(Debug, Clone)]
pub struct ParentControlHandle {
    inner: std::sync::Arc<midl::ServeInner>,
}
impl midl::endpoints::ControlHandle for ParentControlHandle {
    fn shutdown(&self) {
        self.inner.shutdown()
    }
    fn shutdown_with_epitaph(&self, status: fx_status::Status) {
        self.inner.shutdown_with_epitaph(status)
    }
    fn is_closed(&self) -> bool {
        self.inner.channel().is_closed()
    }
    fn on_closed<'a>(&'a self) -> midl::OnSignals<'a> {
        self.inner.channel().on_closed()
    }
}
impl ParentControlHandle {}
#[must_use = "midl methods require a response to be sent"]
#[derive(Debug)]
pub struct ParentGetChildResponder {
    control_handle: std::mem::ManuallyDrop<ParentControlHandle>,
    tx_id: u32,
    ordinal: u64,
}
/// Set the the channel to be shutdown (see [`ParentControlHandle::shutdown`])
/// if the responder is dropped without sending a response, so that the client
/// doesn't hang. To prevent this behavior, call `drop_without_shutdown`.
impl std::ops::Drop for ParentGetChildResponder {
    fn drop(&mut self) {
        self.control_handle.shutdown();
        // Safety: drops once, never accessed again
        unsafe { std::mem::ManuallyDrop::drop(&mut self.control_handle) };
    }
}
impl midl::endpoints::Responder for ParentGetChildResponder {
    type ControlHandle = ParentControlHandle;
    fn control_handle(&self) -> &ParentControlHandle {
        &self.control_handle
    }
    fn drop_without_shutdown(mut self) {
        // Safety: drops once, never accessed again due to mem::forget
        unsafe { std::mem::ManuallyDrop::drop(&mut self.control_handle) };
        // Prevent Drop from running (which would shut down the channel)
        std::mem::forget(self);
    }
}
impl ParentGetChildResponder {
    /// Sends a response to the midl transaction.
    ///
    /// Sets the channel to shutdown if an error occurs.
    pub fn send(self, mut c: midl::endpoints::ClientEnd<ChildMarker>) -> Result<(), midl::Error> {
        let r = self.send_raw(c);
        if r.is_err() {
            self.control_handle.shutdown();
        }
        self.drop_without_shutdown();
        r
    }
    /// Similar to "send" but does not shutdown the channel if
    /// an error occurs.
    pub fn send_no_shutdown_on_err(self, mut c: midl::endpoints::ClientEnd<ChildMarker>) -> Result<(), midl::Error> {
        let r = self.send_raw(c);
        self.drop_without_shutdown();
        r
    }
    fn send_raw(&self, mut c: midl::endpoints::ClientEnd<ChildMarker>) -> Result<(), midl::Error> {
        let msg = midl::encoding::TransactionMessage {
            header: midl::encoding::TransactionHeader::new(
                self.tx_id,
                self.ordinal,
                midl::encoding::DynamicFlags::empty(),
            ),
            body: (c,),
        };
        midl::encoding::with_tls_encode_buf(|bytes, handles| {
            midl::encoding::Encoder::encode::<midl::encoding::TransactionMessageType<ParentGetChildResponse>>(
                bytes, handles, msg,
            )?;
            self.control_handle.inner.send_raw_msg(&*bytes, &mut *handles)
        })
    }
}
#[must_use = "midl methods require a response to be sent"]
#[derive(Debug)]
pub struct ParentGetChildRequestResponder {
    control_handle: std::mem::ManuallyDrop<ParentControlHandle>,
    tx_id: u32,
    ordinal: u64,
}
/// Set the the channel to be shutdown (see [`ParentControlHandle::shutdown`])
/// if the responder is dropped without sending a response, so that the client
/// doesn't hang. To prevent this behavior, call `drop_without_shutdown`.
impl std::ops::Drop for ParentGetChildRequestResponder {
    fn drop(&mut self) {
        self.control_handle.shutdown();
        // Safety: drops once, never accessed again
        unsafe { std::mem::ManuallyDrop::drop(&mut self.control_handle) };
    }
}
impl midl::endpoints::Responder for ParentGetChildRequestResponder {
    type ControlHandle = ParentControlHandle;
    fn control_handle(&self) -> &ParentControlHandle {
        &self.control_handle
    }
    fn drop_without_shutdown(mut self) {
        // Safety: drops once, never accessed again due to mem::forget
        unsafe { std::mem::ManuallyDrop::drop(&mut self.control_handle) };
        // Prevent Drop from running (which would shut down the channel)
        std::mem::forget(self);
    }
}
impl ParentGetChildRequestResponder {
    /// Sends a response to the midl transaction.
    ///
    /// Sets the channel to shutdown if an error occurs.
    pub fn send(self, mut r: midl::endpoints::ServerEnd<ChildMarker>) -> Result<(), midl::Error> {
        let r = self.send_raw(r);
        if r.is_err() {
            self.control_handle.shutdown();
        }
        self.drop_without_shutdown();
        r
    }
    /// Similar to "send" but does not shutdown the channel if
    /// an error occurs.
    pub fn send_no_shutdown_on_err(self, mut r: midl::endpoints::ServerEnd<ChildMarker>) -> Result<(), midl::Error> {
        let r = self.send_raw(r);
        self.drop_without_shutdown();
        r
    }
    fn send_raw(&self, mut r: midl::endpoints::ServerEnd<ChildMarker>) -> Result<(), midl::Error> {
        let msg = midl::encoding::TransactionMessage {
            header: midl::encoding::TransactionHeader::new(
                self.tx_id,
                self.ordinal,
                midl::encoding::DynamicFlags::empty(),
            ),
            body: (r,),
        };
        midl::encoding::with_tls_encode_buf(|bytes, handles| {
            midl::encoding::Encoder::encode::<midl::encoding::TransactionMessageType<ParentGetChildRequestResponse>>(
                bytes, handles, msg,
            )?;
            self.control_handle.inner.send_raw_msg(&*bytes, &mut *handles)
        })
    }
}
