[package]
authors = ["Roland Sz. Kovács <Roland.Szarka-Kovacs@meshx.co>"]
edition = "2021"
name = "package-tool"
version = "0.1.0"

[dependencies]
anyhow = "1.0"
argh = "0.1"
tokio = {version = "1.30", features = ["full"]}
package_tool={path = "../../lib/package-tool", package = "package_tool_lib"}