[package]
name = "component_manager"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
moniker = {version = "0.1.0", path = "../moniker"}
thiserror="1.0.30"

[lib]
crate-type   = ["rlib", "cdylib"]